### ISSUE TITLE
Occurred Error : Could not find partial `Search Box`

### ISSUE THREAD

**Issue by gaon12** [yongxinL/mediawiki-skins-Library#27]
I wanted to use this skin, so I set it up after installation, and the following error occurred.

`Could not compile template skin: Could not find partial Searchbox at /var/www/beta/w/skins/Library/includes/templates/Searchbox.mustache`

What should I do?

**Comment by yongxinL** [comment]
can you check if the file Searchbox.mustache exists in folder includes/templates?

**Comment by gaon12** [comment]
> can you check if the file Searchbox.mustache exists in folder includes/templates?

 I checked and found that searchBox.mustache on the enclosures/templates.

 File SearchBox.mustach, B is in uppercase, so I changed it to lowercase. Then it works. 

So, I think you should change the name SearchBox.mustache to Searchbox.mustache in this repo.
