### ISSUE TITLE
Deprecation warnings in 1.39

### ISSUE THREAD

**Issue by jdlrobson** [yongxinL/mediawiki-skins-Library#36]
Various deprecation warnings in 1.39 appear, related to the  use of the polyfill in Library skin for 1.35
```
<b>Deprecated</b>:  Use of SkinTemplate::buildContentNavigationUrls was deprecated in MediaWiki 1.38. [Called from SkinLibrary::getPortletsTemplateData in /Users/jrobson/git/core/skins/Library/includes/SkinLibrary.php at line 159] in <b>/Users/jrobson/git/core/includes/debug/MWDebug.php</b> on line <b>381</b><br />
<br />
<b>Deprecated</b>:  Use of Skin::bottomScripts was deprecated in MediaWiki 1.37. [Called from SkinLibrary::tailElement in /Users/jrobson/git/core/skins/Library/includes/SkinLibrary.php at line 485] in <b>/Users/jrobson/git/core/includes/debug/MWDebug.php</b> on line <b>381</b><br />
<!DOCTYPE html>
```

Related tasks:
* https://phabricator.wikimedia.org/T306942 
* https://phabricator.wikimedia.org/T300284
* 
I think these can be avoided by dropping support for 1.35 and the polyfill for that version but given the way your code is structured I'm not sure how to do that cleanly. What do you think?

**Comment by yongxinL** [comment]
the skin class need to rewrite and expand from Skin Mustache class in 1.38.

**Comment by yongxinL** [comment]
I found the problem, below two lines need to remove from skin.json
"content": true,
"legacy": true,
so it will be looks like this
    "ResourceModules": {
        "skins.library.styles": {
            "class": "ResourceLoaderSkinModule",
            "features": {
                "normalize": true,
                "elements": true,
                "interface": true,
                "content-parser-output": true
            },
